name: Scheduled Job

on:
  workflow_dispatch:
  schedule:
    # Runs every 5 minutes, which is the shortest interval GitHub Actions allows.
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Check and Install ChromeDriver
        run: |
          CHROMIUM_VERSION=$(chromium-browser --version | grep -oP 'Chromium \K[\d.]+')
          echo "Chromium Version: $CHROMIUM_VERSION"
          CHROMEDRIVER_VERSION=$(echo $CHROMIUM_VERSION | cut -d'.' -f1)
          CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEDRIVER_VERSION"
          LATEST_CHROMEDRIVER_VERSION=$(curl $CHROMEDRIVER_URL)
          echo "Matching ChromeDriver Version: $LATEST_CHROMEDRIVER_VERSION"
          wget -N "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
          unzip -o ~/chromedriver_linux64.zip -d ~/chromedriver/
          sudo mv ~/chromedriver/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run the script
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          VI_USERNAME: ${{ secrets.VI_USERNAME }}
          VI_PASSWORD: ${{ secrets.VI_PASSWORD }}
        run: python -m nba_main

      - name: Commit and push if content changed
        run: |-
             git config user.name "Automated"
             git config user.email "actions@users.noreply.github.com"
             git add -A
             timestamp=$(date -u)
             git commit -m "Latest data: ${timestamp}" || exit 0
             git push